### ISSUE TITLE
Chef::Exceptions::ContentLengthMismatch: Response body length 8006 does not match HTTP Content-Length header 12829

### ISSUE THREAD

**Issue by jp** [chef/chef-zero#126]
When the chef-client is updating inside a docker created by chef provisioning, each time it is synchronizing the yum-epel repo there is this ContentLengthMismatch issue. What is interesting is that it is alway 8006 in the error, but this is not crashing all the time on the same expected filesize. I've experimented that on multiple newly installed environments.

```
$ gem list | grep chef
chef (12.2.1)
chef-provisioning (0.19)
chef-provisioning-docker (0.5.2)
chef-provisioning-vagrant (0.8.3)
chef-zero (4.2.1, 2.2.1)
cheffish (0.10)

```

The error of the chef-client run against the chef-zero inside docker:
```
[2015-04-10T21:50:26+00:00] INFO: Storing updated cookbooks/yum-epel/attributes/epel.rb in the cache.
[2015-04-10T21:50:26+00:00] INFO: Storing updated cookbooks/yum-epel/attributes/default.rb in the cache.
[2015-04-10T21:50:26+00:00] INFO: Storing updated cookbooks/yum-epel/README.md in the cache.
[2015-04-10T21:50:26+00:00] INFO: Storing updated cookbooks/yum-epel/metadata.json in the cache.
[2015-04-10T21:50:26+00:00] INFO: Storing updated cookbooks/yum-epel/attributes/epel-testing.rb in the cache.
[2015-04-10T21:50:26+00:00] INFO: Storing updated cookbooks/yum-epel/CHANGELOG.md in the cache.

================================================================================
Error Syncing Cookbooks:
================================================================================

Unexpected Error:
-----------------
Chef::Exceptions::ContentLengthMismatch: Response body length 8006 does not match HTTP Content-Length header 12829.

[2015-04-10T21:50:26+00:00] ERROR: Running exception handlers
[2015-04-10T21:50:26+00:00] ERROR: Exception handlers complete
[2015-04-10T21:50:26+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-04-10T21:50:26+00:00] ERROR: Response body length 8006 does not match HTTP Content-Length header 12829.
[2015-04-10T21:50:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
STDERR: 
---- End output of docker run --name pupub a438502aa8c76102adf0d7e4e0b9d6421e70dec728c9d19e15f34e304a5688c3 chef-client -l info ----
Ran docker run --name pupub a438502aa8c76102adf0d7e4e0b9d6421e70dec728c9d19e15f34e304a5688c3 chef-client -l info returned 1
[2015-04-10T17:50:27-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Inside docker container:
```
root@8b6cdd10bdc0:/# chef-client -v
Chef: 12.2.1
```

The chef-provisioning script:
```
require 'chef/provisioning/docker_driver'

with_driver 'docker'

machine 'pupub' do
  recipe 'mongodb'

  machine_options :docker_options => {
      :base_image => {
          :name => 'ubuntu',
          :repository => 'ubuntu',
          :tag => '14.04'
      }
  }
end
```

I'm beforehand installing all the dependancies to the mongodb cookbook with berkshelf, vendoring them and setting them in a good place for chef zero.

Here is the complete log for the chef-zero run 
```
[2015-04-10T18:17:16-04:00] INFO: Started chef-zero at http://localhost:8889 with repository at /home/jpellet/.chef/
  One version per cookbook
  acls at /home/jpellet/.chef/acls
  clients at /home/jpellet/.chef/clients
  cookbooks at /home/jpellet/.chef/cookbooks
  containers at /home/jpellet/.chef/containers
  data_bags at /home/jpellet/.chef/data_bags
  environments at /home/jpellet/.chef/environments
  groups at /home/jpellet/.chef/groups
  nodes at /home/jpellet/.chef/nodes
  roles at /home/jpellet/.chef/roles
  policies at /home/jpellet/.chef/policies

[2015-04-10T18:17:16-04:00] INFO: Forking chef instance to converge...
[2015-04-10T18:17:16-04:00] INFO: *** Chef 12.2.1 ***
[2015-04-10T18:17:16-04:00] INFO: Chef-client pid: 26972
[2015-04-10T18:17:17-04:00] INFO: Run List is []
[2015-04-10T18:17:17-04:00] INFO: Run List expands to []
[2015-04-10T18:17:17-04:00] INFO: Starting Chef Run for jpellet
[2015-04-10T18:17:17-04:00] INFO: Running start handlers
[2015-04-10T18:17:17-04:00] INFO: Start handlers complete.
[2015-04-10T18:17:17-04:00] INFO: HTTP Request Returned 404 Not Found : Object not found: /reports/nodes/jpellet/runs
[2015-04-10T18:17:17-04:00] INFO: Loading cookbooks []
[2015-04-10T18:17:17-04:00] WARN: Node jpellet has an empty run list.
[2015-04-10T18:17:17-04:00] INFO: Processing machine[pupub] action converge (@recipe_files::/home/jpellet/dev/ci/ubuntu-pup.rb line 5)
[2015-04-10T18:17:17-04:00] INFO: Processing chef_node[pupub] action create (basic_chef_client::block line 64)
[2015-04-10T18:17:17-04:00] INFO: Processing chef_node[pupub] action create (basic_chef_client::block line 64)
[2015-04-10T18:17:18-04:00] INFO: Processing chef_client[pupub] action create (basic_chef_client::block line 131)
[2015-04-10T18:17:18-04:00] INFO: Processing chef_node[pupub] action create (basic_chef_client::block line 142)
[2015-04-10T18:17:24-04:00] INFO: Processing chef_node[pupub] action create (basic_chef_client::block line 64)
[2015-04-10T18:17:24-04:00] INFO: Converging pupub because the resource was updated ...
[0m
================================================================================[0m
[31mError executing action `converge` on resource 'machine[pupub]'[0m
================================================================================[0m

[0mMixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '1'
[0m---- Begin output of docker run --name pupub 2c7472277e6e56221b1b970a7c8f1e6da27a33b41788a31f6f82747a18d89224 chef-client -l info ----
[0mSTDOUT: [2015-04-10T22:17:29+00:00] INFO: Forking chef instance to converge...
[0m[2015-04-10T22:17:29+00:00] INFO: *** Chef 12.2.1 ***
[0m[2015-04-10T22:17:29+00:00] INFO: Chef-client pid: 10
[0m[2015-04-10T22:17:30+00:00] INFO: Run List is [recipe[mongodb], recipe[pup]]
[0m[2015-04-10T22:17:30+00:00] INFO: Run List expands to [mongodb, pup]
[0m[2015-04-10T22:17:30+00:00] INFO: Starting Chef Run for pupub
[0m[2015-04-10T22:17:30+00:00] INFO: Running start handlers
[0m[2015-04-10T22:17:30+00:00] INFO: Start handlers complete.
[0m[2015-04-10T22:17:30+00:00] INFO: HTTP Request Returned 404 Not Found : Object not found: /reports/nodes/pupub/runs
[0m[2015-04-10T22:17:32+00:00] INFO: Loading cookbooks [mongodb@0.16.2, pup@0.1.0, apt@2.7.0, yum@3.5.4, python@1.4.6, runit@1.5.18, build-essential@2.2.2, yum-epel@0.6.0]
[0m[0m
[0m================================================================================[0m
[0m[31mError Syncing Cookbooks:[0m
[0m================================================================================[0m
[0m
[0m[0mUnexpected Error:[0m
[0m-----------------[0m
[0mChef::Exceptions::ContentLengthMismatch: Response body length 8006 does not match HTTP Content-Length header 15655.[0m
[0m
[0m[0m[2015-04-10T22:17:33+00:00] ERROR: Running exception handlers
[0m[2015-04-10T22:17:33+00:00] ERROR: Exception handlers complete
[0m[2015-04-10T22:17:33+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[0m[2015-04-10T22:17:33+00:00] ERROR: Response body length 8006 does not match HTTP Content-Length header 15655.
[0m[2015-04-10T22:17:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[0mSTDERR: 
[0m---- End output of docker run --name pupub 2c7472277e6e56221b1b970a7c8f1e6da27a33b41788a31f6f82747a18d89224 chef-client -l info ----
[0mRan docker run --name pupub 2c7472277e6e56221b1b970a7c8f1e6da27a33b41788a31f6f82747a18d89224 chef-client -l info returned 1[0m

[0mResource Declaration:[0m
---------------------[0m
# In /home/jpellet/dev/ci/ubuntu-pup.rb
[0m
[0m  5: machine 'pupub' do
[0m  6:   recipe 'mongodb'
[0m  7:   recipe 'pup'
[0m  8: 
[0m  9:   machine_options :docker_options => {
[0m 10:       :base_image => {
[0m 11:           :name => 'ubuntu',
[0m 12:           :repository => 'ubuntu',
[0m 13:           :tag => '14.04'
[0m 14:       }
[0m 15:   }
[0m 16: end
[0m 17: 
[0m
[0mCompiled Resource:[0m
------------------[0m
# Declared in /home/jpellet/dev/ci/ubuntu-pup.rb:5:in `from_file'
[0m
[0mmachine("pupub") do
[0m  action :converge
[0m  retries 0
[0m  retry_delay 2
[0m  default_guard_interpreter :default
[0m  chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"jpellet", :signing_key_filename=>"/home/jpellet/.chef/jpellet.pem"}}
[0m  driver "docker"
[0m  machine_options {:docker_options=>{:base_image=>{:name=>"ubuntu", :repository=>"ubuntu", :tag=>"14.04"}}}
[0m  declared_type :machine
[0m  cookbook_name "@recipe_files"
[0m  recipe_name "/home/jpellet/dev/ci/ubuntu-pup.rb"
[0m  run_list_modifiers [#<Chef::RunList::RunListItem:0x007fd708708960 @version=nil, @type=:recipe, @name="mongodb">, #<Chef::RunList::RunListItem:0x007fd7087085a0 @version=nil, @type=:recipe, @name="pup">]
[0mend
[0m
[0m[2015-04-10T18:17:33-04:00] INFO: Running queued delayed notifications before re-raising exception
[2015-04-10T18:17:33-04:00] ERROR: Running exception handlers
[2015-04-10T18:17:33-04:00] ERROR: Exception handlers complete
[2015-04-10T18:17:33-04:00] FATAL: Stacktrace dumped to /home/jpellet/.chef/local-mode-cache/cache/chef-stacktrace.out
[2015-04-10T18:17:33-04:00] ERROR: machine[pupub] (@recipe_files::/home/jpellet/dev/ci/ubuntu-pup.rb line 5) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of docker run --name pupub 2c7472277e6e56221b1b970a7c8f1e6da27a33b41788a31f6f82747a18d89224 chef-client -l info ----
STDOUT: [2015-04-10T22:17:29+00:00] INFO: Forking chef instance to converge...
[2015-04-10T22:17:29+00:00] INFO: *** Chef 12.2.1 ***
[2015-04-10T22:17:29+00:00] INFO: Chef-client pid: 10
[2015-04-10T22:17:30+00:00] INFO: Run List is [recipe[mongodb], recipe[pup]]
[2015-04-10T22:17:30+00:00] INFO: Run List expands to [mongodb, pup]
[2015-04-10T22:17:30+00:00] INFO: Starting Chef Run for pupub
[2015-04-10T22:17:30+00:00] INFO: Running start handlers
[2015-04-10T22:17:30+00:00] INFO: Start handlers complete.
[2015-04-10T22:17:30+00:00] INFO: HTTP Request Returned 404 Not Found : Object not found: /reports/nodes/pupub/runs
[2015-04-10T22:17:32+00:00] INFO: Loading cookbooks [mongodb@0.16.2, pup@0.1.0, apt@2.7.0, yum@3.5.4, python@1.4.6, runit@1.5.18, build-essential@2.2.2, yum-epel@0.6.0]
[0m
================================================================================[0m
[31mError Syncing Cookbooks:[0m
================================================================================[0m

[0mUnexpected Error:[0m
-----------------[0m
Chef::Exceptions::ContentLengthMismatch: Response body length 8006 does not match HTTP Content-Length header 15655.[0m

[0m[2015-04-10T22:17:33+00:00] ERROR: Running exception handlers
[2015-04-10T22:17:33+00:00] ERROR: Exception handlers complete
[2015-04-10T22:17:33+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-04-10T22:17:33+00:00] ERROR: Response body length 8006 does not match HTTP Content-Length header 15655.
[2015-04-10T22:17:33+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
STDERR: 
---- End output of docker run --name pupub 2c7472277e6e56221b1b970a7c8f1e6da27a33b41788a31f6f82747a18d89224 chef-client -l info ----
Ran docker run --name pupub 2c7472277e6e56221b1b970a7c8f1e6da27a33b41788a31f6f82747a18d89224 chef-client -l info returned 1
[2015-04-10T18:17:33-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

Downgrading chef to 11.18.6 is giving me a the same error but the size is 8038.

```
[2015-04-11T01:00:01+00:00] INFO: Storing updated cookbooks/yum/templates/default/main.erb in the cache.
[2015-04-11T01:00:01+00:00] INFO: Storing updated cookbooks/yum/templates/default/repo.erb in the cache.
[2015-04-11T01:00:01+00:00] INFO: Storing updated cookbooks/yum/metadata.json in the cache.
[2015-04-11T01:00:01+00:00] INFO: Storing updated cookbooks/yum/CHANGELOG.md in the cache.
[2015-04-11T01:00:01+00:00] INFO: Storing updated cookbooks/yum/README.md in the cache.

================================================================================
Error Syncing Cookbooks:
================================================================================

Unexpected Error:
-----------------
Chef::Exceptions::ContentLengthMismatch: Response body length 8038 does not match HTTP Content-Length header 15655.

[2015-04-11T01:00:01+00:00] ERROR: Running exception handlers
[2015-04-11T01:00:01+00:00] ERROR: Exception handlers complete
[2015-04-11T01:00:01+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-04-11T01:00:01+00:00] ERROR: Response body length 8038 does not match HTTP Content-Length header 15655.
[2015-04-11T01:00:01+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
STDERR: 
---- End output of docker run --name web_server6 f5fe504625ca91b2b41cf292d37868855328d67714451e3c1bf19b46b5a45e0f chef-client -l auto ----
Ran docker run --name web_server6 f5fe504625ca91b2b41cf292d37868855328d67714451e3c1bf19b46b5a45e0f chef-client -l auto returned 1
[2015-04-10T21:00:02-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

When I'm loading chef-zero on the side with the following command: ```chef-zero  -l info -H 0.0.0.0```

Then uploading all the cookbooks using the chef-zero playground.

I can do a ```chef-client -r "nginx"``` within my docker container and it works well. I don't understand the issue with chef-provisioning ... how do I get the chef-zero debug logs when doing ```CHEF_DRIVER=docker bundle exec chef-client -z example.rb -l debug``` ? I only get the chef-client debug logs.

This is all working fine when I'm using the chef-server to serve the cookbooks, this is why it seems that it is really related to chef-zero.

**Comment by kri5** [comment]
I Got the same issue, i have some working cookbooks and recipe using chef-provisioning, it works fine with vagrant driver, but with the docker one, i encounter the contentlengthmismatch error.

Any idea?

**Comment by jkeiser** [comment]
Issue #38 has a fix in https://github.com/chef/chef-provisioning-docker/tree/jk/issue38  but it's as-yet untested.  If anyone here can test it out, that would be super appreciated.  cc @kri5 @jp

**Comment by jkeiser** [comment]
This is fixed in chef/chef-provisioning-docker#39.  Please reopen or let us know if it isn't working :)  A new `chef-provisioning-docker` version has been released with this included (gem install should do you).

**Comment by jp** [comment]
Thanks a lot @jkeiser I will check that (at some point) and let you know if I have the issue again.

**Comment by skeenan947** [comment]
@jkeiser I'm getting the same error with chef-provisioning-fog...

**Comment by chriscameron** [comment]
Is this bug open somewhere else? I've run into this error using the following provisioners: AWS, Digital Ocean / Fog, SSH. This really needs to be fixed as when the machine gets into this state re-running doesn't appear to fix.

**Comment by georeith** [comment]
Also getting this error with the AWS provisioner, re-running seems to make it disappear.

**Comment by Paul424** [comment]
Just a heads-up for others that encounter this issue; updating the ChefDK to latest or current (channel) has no use if your actually using chef from a ruby version managed by rvm..... I actually had success after running bundle update which upgraded: chef-zero 4.2.3 (was 4.0) and net-ssh 2.9.4 (was 2.9.2) and chef 12.1.2 (was 12.1.1). Thanks all for the detailed investigation on this subject!
